---
title: "Assignments"
toc-title: "Overview"
toc-location: left
jupyter: python3
---

# **Assignment details** 
::: {.callout-tip collapse=false}
## Contents
- [Weekly Homeworks](#weekly)
- [Final Project](#finalProject)
- [Final Exam](#finalExam)

:::

<!--#################################################-->

### Weekly Homeworks {#weekly}
To practice writing Python code, exploring datasets, and running statistical models you will complete a series of weekly homeworks.

There are 3 weekly homeworks to be undertaken with your group and these will be graded using a check system:

* 5/5: Problem set is 100% completed. Every question was attempted and answered, and most answers are correct. Document is clean and easy to follow. Work is exceptional. I will not assign these often.
* 3/5: Problem set is 70–99% complete and most answers are correct. **This is the expected level of performance**.
* 1/5: Problem set is less than 70% complete and/or most answers are incorrect. This indicates that you need to improve next time. I will hopefully not assign these often.

<!--#################################################-->

### Final Project {#finalProject}

At the end of the course, you will demonstrate your knowledge by working on a group assignment… Complete details for the final project will be made available here.


<!--#################################################-->

### Final Exam {#finalExam}

There will be a final exam that will cover:

- 1. Programming in Python (about a third of total marks)
- 2. the core statistical tools of inferential statistics and linear models.

You will take the final exam in-person in a lecture theatre. This is a closed-book, 1.5-hour exam. A formula sheet will be provided, but you will not have online access to Google.


<!--#################################################-->

# **Homeworks** 

<!--#################################################-->


### Homework 1 {#homework1}
::: {.callout-tip collapse=false}
## Contents
- [`homework1`](#HWrmd1)
- [Instructions](#instructions1)
- [Rubric](#rubric1)

---

## `homework1` {#HWrmd1}

You will be working on the `session2-workshop1.zip` file that contains all necessary session files (data, code, etc.).

You can download the zip file from Canvas, or by pulling from the course Github repo. Alternatively, open everything within VScode.

---

## Instructions {#instructions1}

- Finish the assignment and submit your work as a **knitted HTML or PDF file** on Canvas.
- Submit your work **without any of the text provided in the homework file** – include only your code, plots, and explanations/stories.

---

## Rubric {#rubric1}

- **Check minus (1/5):**  
  Displays minimal effort. Doesn’t complete all components. Code is poorly written and not documented. Uses the same type of plot for each graph, or doesn’t use plots appropriate for the variables being analysed.

- **Check (3/5):**  
  Solid effort. Hits all the elements. No clear mistakes. Easy to follow, both the code and the output.

- **Check plus (5/5):**  
  Finished all components of the assignment correctly and addressed both challenges. Code is well-documented. Graphs and tables are properly labelled. Analysis is clear and easy to follow, either because graphs are labeled clearly or additional text describes how to interpret the output.

:::



<!--#################################################-->

### Homework 2 {#homework2}
::: {.callout-tip collapse=false}
## Contents
- [`homework2`](#HWrmd2)
- [Instructions](#instructions2)
- [Rubric](#rubric2)

---

## `homework2` {#HWrmd2}

You will be working the `session4-workshop2.zip` file that contains all necessary session files (data, code, etc.).

You can download the zip file from Canvas, or by pulling from the course Github repo. Alternatively, open everything within VScode.

---

## Instructions {#instructions2}

- Finish the assignment and submit your work as a **knitted HTML or PDF file** on Canvas.
- Submit your work **without any of the text provided in the homework file** – include only your code, plots, and explanations/stories.

---

## Rubric {#rubric2}

- **Check minus (1/5):**  
  Displays minimal effort. Doesn’t complete all components. Code is poorly written and not documented. Uses the same type of plot for each graph, or doesn’t use plots appropriate for the variables being analysed.

- **Check (3/5):**  
  Solid effort. Hits all the elements. No clear mistakes. Easy to follow, both the code and the output.

- **Check plus (5/5):**  
  Finished all components of the assignment correctly and addressed both challenges. Code is well-documented. Graphs and tables are properly labelled. Analysis is clear and easy to follow, either because graphs are labeled clearly or additional text describes how to interpret the output.

:::

<!--#################################################-->


### Homework 3 {#homework3}
::: {.callout-tip collapse=false}
## Contents
- [`homework3`](#HWrmd3)
- [Instructions](#instructions3)
- [Rubric](#rubric3)

---

## `homework3` {#HWrmd3}

You will be working the `session6-workshop3.zip` file that contains all necessary session files (data, code, etc.).

You can download the zip file from Canvas, or by pulling from the course Github repo. Alternatively, open everything within VScode.

---

## Instructions {#instructions3}

- Finish the assignment and submit your work as a **knitted HTML or PDF file** on Canvas.
- Submit your work **without any of the text provided in the homework file** – include only your code, plots, and explanations/stories.

---

## Rubric {#rubric3}

- **Check minus (1/5):**  
  Displays minimal effort. Doesn’t complete all components. Code is poorly written and not documented. Uses the same type of plot for each graph, or doesn’t use plots appropriate for the variables being analysed.

- **Check (3/5):**  
  Solid effort. Hits all the elements. No clear mistakes. Easy to follow, both the code and the output.

- **Check plus (5/5):**  
  Finished all components of the assignment correctly and addressed both challenges. Code is well-documented. Graphs and tables are properly labelled. Analysis is clear and easy to follow, either because graphs are labeled clearly or additional text describes how to interpret the output.

:::






